project:
  type: website
  output-dir: docs

website:
  title: "STAT150: R for Data Science"
  description: "ğŸ§Expedition to R: In the Footsteps of the Palmer Penguins at Kyiv School of Economics, Autumn 2025."
  site-url: "https://kse-stat150-r4ds.github.io"

  repo-url: https://github.com/aranaur/kse-stat150-r4ds.github.io
  repo-actions: [edit, issue]

  sidebar:
    background: "#F0F4F8"
    logo: "images/logo.png"
    pinned: true
    align: center

    tools:
      - icon: backpack2
        href: https://teaching.kse.org.ua/course/view.php?id=3374
        text: "Moodle"
      - icon: github
        href: https://github.com/Aranaur/kse-stat150-r4ds

    style: docked
    search: true
    collapse-level: 1


    contents:
      - section: "ğŸ‘‹Course information"
        contents:
          - href: index.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-team.qmd
            text: Teaching team
          # - href: schedule.qmd
          #   text: Schedule
          - href: course-links.qmd
            text: Useful links
      - section: "ğŸ“œ Slides"
        contents:          
          - href: lectures/lecture-0.qmd
            text: 00 - Hello there!
          - href: lectures/lecture-1.qmd
            text: 01 - Introduction to R and RStudio
          - href: lectures/lecture-2.qmd
            text: 02 - Data Wrangling with Tidyverse
          - href: lectures/lecture-3.qmd
            text: 03 - Reproducible Research with Quarto
          - href: lectures/lecture-4.qmd
            text: 04 - Data Visualization with ggplot2
          - href: lectures/lecture-5.qmd
            text: 05 - Web Scraping and APIs
          - href: lectures/lecture-6.qmd
            text: 06 - Advanced Data Manipulation
          - href: lectures/lecture-7.qmd
            text: 07 - Spatial Data Analysis in R
      - section: "ğŸ‹ï¸ Weekly assignments"
        contents:
          - href: assignments/lab-1.qmd
            text: 01 - Welcome to R
          - href: assignments/lab-2.qmd
            text: 02 - Data Wrangling & Tidying with Tidyverse
          - href: assignments/lab-3.qmd
            text: 03 - Reproducible publishing with Quarto
          - href: assignments/lab-4.qmd
            text: 04 - Data Visualization with ggplot2
          - href: assignments/lab-5.qmd
            text: 05 - Web Scraping and APIs
          - href: assignments/lab-6.qmd
            text: 06 - Advanced Imports and Data Manipulations
          - href: assignments/lab-7.qmd
            text: 07 - Spatial analysis in R
      - href: "final-project.qmd"
        text: "ğŸ› ï¸Final Project"
      - href: "computing-cheatsheets.qmd"
        text: "âœï¸Cheatsheets"

  page-footer:
    right: "This page is built with ğŸ¤ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2026, Ihor Miroshnychenko"
    background: "#263238"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    linkcolor: "#E65100"
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto



